### ISSUE TITLE
Clearing the summary screen at the end of a print

### ISSUE THREAD

**Issue by Soygen** [vvuk/cassini#1]
Hey, this is the guy with the Mars 4 Ultra from Reddit. Figured here is a better place to provide feedback.

Currently, when the print ends, the printers has a summary of how long the print took(pic below). I assume the same happens on the Saturn 3U. This keeps the printer in status 1 and doesn't allow to upload while that summary screen is up. Is there a way to clear that screen via the protocol or do I have to manually hit 'confirm' on the printer itself?

![image](https://github.com/vvuk/cassini/assets/61511681/1f05483c-98e2-4838-9c80-36901823d2c4)

**Comment by vvuk** [comment]
Sadly no -- you have to manually clear it. I think this is intentional, so you can't accidentally start a print while a previous one is still on the plate.

Edit: but yeah it doesn't make sense for uploads 🤷

**Comment by Soygen** [comment]
Yeah, it's not a big deal I guess as you clearly have to be physically near the printer to clear the plate, but of  course I'll forget to hit confirm many times I'm sure!

Thanks for the response.
